# Generated by Django 5.1.5 on 2025-03-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HumanResource",
            fields=[
                ("hr_id", models.AutoField(primary_key=True, serialize=False)),
                ("username_hr", models.CharField(max_length=150, unique=True)),
                ("password_hr", models.CharField(max_length=255)),
                ("email_hr", models.EmailField(max_length=254, unique=True)),
                ("name_hr", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("job_title", models.CharField(max_length=255)),
                ("department", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                ("partner_id", models.AutoField(primary_key=True, serialize=False)),
                ("username_pn", models.CharField(max_length=150, unique=True)),
                ("password_pn", models.CharField(max_length=255)),
                ("name_en", models.CharField(blank=True, max_length=255, null=True)),
                ("name_th", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("agencies", models.CharField(blank=True, max_length=255, null=True)),
                ("province", models.CharField(blank=True, max_length=255, null=True)),
                ("description_pn", models.TextField(blank=True, null=True)),
                ("district", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subdistrict",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("road", models.CharField(blank=True, max_length=255, null=True)),
                ("soi", models.CharField(blank=True, max_length=255, null=True)),
                ("moo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "building_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postal_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("related_fields", models.TextField(blank=True, null=True)),
                ("email_pn", models.EmailField(max_length=254, null=True, unique=True)),
                (
                    "image_pn",
                    models.ImageField(
                        blank=True, null=True, upload_to="partner_images/"
                    ),
                ),
                ("walfare_benefits", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.AutoField(primary_key=True, serialize=False)),
                ("studentname_th", models.CharField(max_length=255)),
                ("studentname_en", models.CharField(max_length=255)),
                ("student_email", models.EmailField(max_length=254, unique=True)),
                ("student_phone", models.CharField(max_length=20)),
                ("degree", models.CharField(max_length=255)),
                ("academic_year", models.CharField(max_length=4)),
                ("gpa", models.FloatField()),
                ("address", models.TextField()),
                ("program", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_name", models.CharField(max_length=255)),
                ("job_posted", models.DateTimeField(auto_now_add=True)),
                ("job_description", models.TextField()),
                ("job_skill", models.TextField()),
                ("job_major", models.CharField(max_length=255)),
                ("job_welfare_benefits", models.CharField(max_length=2000)),
                (
                    "hr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.humanresource",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="humanresource",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.partner"
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("review_text", models.TextField()),
                ("review_date", models.DateTimeField(auto_now_add=True)),
                ("rating", models.IntegerField()),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.partner"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jobposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.job",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.student",
                    ),
                ),
            ],
        ),
    ]
